version: "3"

services:
  build-bundle:
    build: .
    volumes:
      # Place a single GTFS ZIP file in the `./bundle`
      # directory, then run this service to build a
      # bundle from it, output to the same directory
      - ./bundle:/bundle
    # Command needs to be wrapped in `sh`, since otherwise
    # the subshell command doesn't work
    # Also, the JAR must be executed from within the same
    # directory as the bundle, or else some necessary files
    # are not generated
    command: ["sh", "-c", "cd /bundle && java -Xss4m -Xmx3G -jar /app/onebusaway-transit-data-federation-builder-2.0.1-SNAPSHOT-withAllDependencies.jar $$(ls /bundle/*.zip) ."]

  mysql:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      # These are the settings that the OBA image expects
      # There is no password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    restart: always


  oba:
    depends_on:
      # Automatically bring up the database service first
      - mysql
    build: .
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/mydatabase
      JDBC_USER: user
      JDBC_PASSWORD: userpassword
    volumes:
      # Share the host's `bundle` directory with the
      # filesystem of the OBA service
      - ./bundle:/bundle
    ports:
      # Access the webapp on your host machine at a path like
      # http://localhost:8888/onebusaway-api-webapp/api/where/agency/${YOUR_AGENCY}.json?key=TEST
      - "8888:8080"

volumes:
  mysql-data: