version: "3"

services:
  # build-bundle:
  #   build: .
  #   volumes:
  #     # Place a single GTFS ZIP file in the `./bundle`
  #     # directory, then run this service to build a
  #     # bundle from it, output to the same directory
  #     - ./bundle:/bundle
  #   # Command needs to be wrapped in `sh`, since otherwise
  #   # the subshell command doesn't work
  #   # Also, the JAR must be executed from within the same
  #   # directory as the bundle, or else some necessary files
  #   # are not generated
  #   command: ["sh", "-c", "cd /bundle && java -Xss4m -Xmx3G -jar /app/onebusaway-transit-data-federation-builder-2.0.1-SNAPSHOT-withAllDependencies.jar $$(ls /bundle/*.zip) ."]

  oba_database:
    image: mysql:8.3
    container_name: oba_database
    environment:
      MYSQL_ROOT_PASSWORD: Ins3cure!
      MYSQL_DATABASE: oba_database
      MYSQL_USER: oba_user
      MYSQL_PASSWORD: oba_password
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    restart: always

  oba_app:
    container_name: oba_app
    depends_on:
      - oba_database
    build: .
    environment:
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      JDBC_URL: jdbc:mysql://oba_database:3306/oba_database
      JDBC_USERNAME: oba_user
      JDBC_PASSWORD: oba_password
    volumes:
      # Share the host's `bundle` and `oba_config' directories
      # with the filesystem of the OBA service.
      - ./oba_config:/oba_config
    ports:
      # Access the webapp on your host machine at a path like
      # http://localhost:8080/onebusaway-api-webapp/api/where/agency/${YOUR_AGENCY}.json?key=TEST
      - "8080:8080"
    # restart: always

volumes:
  mysql-data: